# Generated by Django 2.1.5 on 2019-09-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='picture',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
