# Generated by Django 2.1.5 on 2019-09-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20190922_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='picture',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
